plugin_spec_version: v1 
name: example_types
title: "Example Types"
description: "Example plugin that demonstrates multiple input and output types"
version: 0.3.0
vendor: demo
tags: ["komand", "example"]
icon: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDIwLjEuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgd2lkdGg9IjE0MC41cHgiCgkgaGVpZ2h0PSIxMDBweCIgdmlld0JveD0iMCAwIDE0MC41IDEwMCIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+CjxnIGlkPSJrb21hbmRfaWNvbiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTQ4LjEsIC00OS42KSI+Cgk8cmVjdCB4PSIxNjcuNSIgeT0iNTEuMiIgZmlsbD0iI0ZGRkZGRiIgd2lkdGg9IjE5LjMiIGhlaWdodD0iOTguNCIvPgoJPHBvbHlnb24gZmlsbD0iI0ZGRkZGRiIgcG9pbnRzPSIxMjguOSw1MSAxMjEuNSw1MSAxMTQuOSw1MSAxNTAuNCwxMDAuOSAxMTQuOSwxNTEgMTIxLjQsMTUxIDEyOC45LDE1MSAxNjQuNCwxMDAuOSAJIi8+Cgk8cG9seWdvbiBvcGFjaXR5PSIwLjciIGZpbGw9IiNGRkZGRkYiIHBvaW50cz0iMTAyLjksNTEgOTUuNSw1MSA4OC45LDUxIDEyNC40LDEwMC45IDg4LjksMTUxIDk1LjQsMTUxIDEwMi45LDE1MSAxMzguNCwxMDAuOSAJIi8+Cgk8cG9seWdvbiBvcGFjaXR5PSIwLjM1IiBmaWxsPSIjRkZGRkZGIiBwb2ludHM9IjgyLjksNTEgNzUuNSw1MSA2OC45LDUxIDEwNC40LDEwMC45IDY4LjksMTUxIDc1LjQsMTUxIDgyLjksMTUxIDExOC40LDEwMC45IAkiLz4KCTxwb2x5Z29uIG9wYWNpdHk9IjAuMTUiIGZpbGw9IiNGRkZGRkYiIHBvaW50cz0iNjIuOSw1MSA1NS41LDUxIDQ4LjksNTEgODQuNCwxMDAuOSA0OC45LDE1MSA1NS40LDE1MSA2Mi45LDE1MSA5OC40LDEwMC45IAkiLz4KCTxwb2x5Z29uIGZpbGw9IiNGRkZGRkYiIHBvaW50cz0iMTIyLjksNTEgMTE1LjUsNTEgMTA4LjksNTEgMTQ0LjQsMTAwLjkgMTA4LjksMTUxIDExNS40LDE1MSAxMjIuOSwxNTEgMTU4LjQsMTAwLjkgCSIvPgo8L2c+Cjwvc3ZnPgo="
help: |
  ## About
  Example plugin for testing.

  ## Actions
  ### Many Types
  This action is used to lots of different input types with some default values and concatenates all inputs into the output string.

  #### Input

  |Name|Type|Default|Required|Description|Enum|
  |----|----|-------|--------|-----------|----|
  |enum|string|cantelope|False|None|['apple', 'banana', 'cantelope', 'date']|
  |string|string|DefaultString|False|None|None|
  |object|object|None|False|None|None|
  |bytes|bytes|None|False|None|None|
  |number|number|123.456|False|None|None|
  |string_array|[]string|None|False|None|None|
  |thing|thing_struct|None|False|None|None|
  |boolean|boolean|True|False|None|None|
  |file|file|None|False|None|None|
  |integer|integer|123|False|None|None|
  |date|date|None|False|None|None|
  |integer_array|[]integer|None|False|None|None|

  #### Output

  |Name|Type|Required|Description|
  |----|----|--------|-----------|
  |enum|string|False|None|
  |string|string|False|None|
  |object|object|False|None|
  |bytes|bytes|False|None|
  |number|number|False|None|
  |string_array|[]string|False|None|
  |thing|thing_struct|False|None|
  |boolean|boolean|False|None|
  |file|file|False|None|
  |integer|integer|False|None|
  |date|date|False|None|
  |integer_array|[]integer|False|None|
  |aggregated|string|False|All inputs, concatenated|

  ## Triggers
  ### Many Types
  This trigger is used to lots of different input types with no default values and concatenates all inputs into the output string.

  #### Input

  |Name|Type|Default|Required|Description|Enum|
  |----|----|-------|--------|-----------|----|
  |interval|integer|15|False|How often (in seconds) to trigger a workflow|None|
  |string|string|None|False|None|None|
  |enum|string|None|False|None|['apple', 'banana', 'cherry', 'date']|
  |bytes|bytes|None|False|None|None|
  |number|number|None|False|None|None|
  |object|object|None|False|None|None|
  |string_array|[]string|None|False|None|None|
  |thing|thing_struct|None|False|None|None|
  |boolean|boolean|None|False|None|None|
  |file|file|None|False|None|None|
  |integer|integer|None|False|None|None|
  |date|date|None|False|None|None|
  |integer_array|[]integer|None|False|None|None|

  #### Output

  |Name|Type|Required|Description|
  |----|----|--------|-----------|
  |enum|string|False|None|
  |string|string|False|None|
  |object|object|False|None|
  |bytes|bytes|False|None|
  |number|number|False|None|
  |string_array|[]string|False|None|
  |thing|thing_struct|False|None|
  |boolean|boolean|False|None|
  |file|file|False|None|
  |integer|integer|False|None|
  |date|date|False|None|
  |integer_array|[]integer|False|None|
  |aggregated|string|False|All inputs, concatenated|

  ## Connection
  This plugin does not contain a connection.
  ## Troubleshooting
  This plugin does not contain any troubleshooting information.

  ## Workflows
  Examples:
  * Testing

  ## References
  * [Komand](https://www.komand.com/)

types:
  thing_struct:
    strval: 
      type: string
      description: "a string"
    intval: 
      type: integer
      description: "an integer"
  file:
    content:
      type: bytes
      description: "the raw content, in bytes"
    filename:
      type: string
      description: "the filename"

triggers:
  many_types_trigger:
    name: "Many Types Trigger"
    description: "Lots of different input types. No default values. This concatenates all inputs into the output string."
    input:
      interval:
        description: "How often (in seconds) to trigger a workflow"
        type: integer
        default: 15
      string:
        type: string
      integer:
        type: integer
      number:
        type: number
      boolean:
        type: boolean
      enum:
        type: string
        enum:
          - "apple"
          - "banana"
          - "cherry"
          - "date"
      date:
       type: date
      bytes:
        type: bytes
      string_array:
        type: "[]string"
      integer_array:
        type: "[]integer"
      object:
        type: object
      file:
        type: file
      thing:
        type: thing_struct
    output:
      aggregated: 
        type: string
        description: "All inputs, concatenated"
      string:
        type: string
      integer:
        type: integer
      number:
        type: number
      boolean:
        type: boolean
      enum:
        type: string
      date:
        type: date
      bytes:
        type: bytes
      string_array:
        type: "[]string"
      integer_array:
        type: "[]integer"
      object:
        type: object
      file:
        type: file
      thing:
        type: thing_struct
actions:
  many_types_action:
    name: "Many Types with Defaults"
    description: "Lots of different input types with some default values. This concatenates all inputs into the output string."
    input:
      string:
        type: string
        default: "DefaultString"
      integer:
        type: integer
        default: 123
      number:
        type: number
        default: 123.456        
      boolean:
        type: boolean
        default: true
      enum:
        type: string
        default: "cantelope"
        enum:
          - "apple"
          - "banana"
          - "cantelope"
          - "date"
      date:
        type: date
      bytes:
        type: bytes
      string_array:
        type: "[]string"
      integer_array:
        type: "[]integer"
      object:
        type: object
      file:
        type: file
      thing:
        type: thing_struct
    output:
      aggregated: 
        type: string
        description: "All inputs, concatenated"
      string:
        type: string
      integer:
        type: integer
      number:
        type: number        
      boolean:
        type: boolean
      enum:
        type: string
      date:
        type: date
      bytes:
        type: bytes
      string_array:
        type: "[]string"
      integer_array:
        type: "[]integer"
      object:
        type: object
      file:
        type: file
      thing:
        type: thing_struct
