plugin_spec_version: v2
name: timers
title: "Timers"
description: "A variety of time-based triggers"
version: 0.2.0
vendor: komand
tags: ["timer", "time", "cron"]
icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAgAElEQVR42u2de5CeVZ3nP+etrq6urt6e3kyqK5vNxlQ2m4mZDIORzWA2G5kYIgOI4Y7IHQICyl1QwZ1iWTbDIDIMOmxkEAEVFZFrQrgjF7kpRC4hImQgQgwxhNh0QpN093f/OL8emtiddL/v85zndr5Vb3WCdt7nOef8vud3/zkiKgFJNaAFmA5MBjqBJvufNwHrgZeBNUCvc64/rlpERMGFXlKHpGMk3S9ps3aOP0q6W9I5kiZJaoorGZH3g94kqUVSm/2sSaryeiBpvKRLJL2l+vG+pDskzZfUEs+ZBjSp0sAVTIVtBdqA8cAUYBLwX4Bx9ukANpg6uwF43dTaVfb3Lufc1pIf0nbgC8CZtiZJoB9YBnwVWFlm88DOWZudpSnAVPvzn9vPFqAH6AK6gXeAV+ycbbL/1lOUNXI534wWE/ZZwN8CM8yG7ajjAL8BPAc8BjwAvOyc21Sm28nW5jJgAZDGTbUOOB+43jnXWyYN0s7ZbOBTwG4m+K2jPGPrgNeAFcD9wDN2GW1xzkUCGMVmTALmAwcCM4ExCX9Nr5HBPcCP7VbbWuADXLP1WmJrlya2ABcD3yi6NiVpLLAHcLD97Ez4KzYCLwB3A7cDrzjneqLRPvRmNEuaI+mGBu3W0eJds3MXSmorovDbs/8+4Jq9J+kCSc0FteMnSTpX0q8l9QVas3ck3SXpOEkTquyj2n5DWiXtZUL4rrLD+5IelLSfpNYCrd/8wIQ5gM2STimSU8wE7yuSXg0o+EPhVUkXSppc9Rt/oQnde8oP3pO01LSRWs7XcJqklzJcq7clzS/AWWuTdKKtVV+OztrvJF0uaWrVhH+GpBtHGJfOCu9IukJSZ07XsFXSbTlYp19LmpBj82iO5UC8n+Oz9qZpJh1lF/wOSV+zFy4C+iQ9KWm3PNlsZsceIWlbTtbpirwlDNmtf4FpKUXANklPm1bcVDbBR9I8e8FtKh7eknRCXjZG0hhJL+ZofTZLmp2j8zZZ0r0FPWubJV0raVyItaoF2Ixm4AzgZnx8tYjs1gl8G1hiiTZZYw9gWo7WpxU4PeuogF00c4F78WHRIp61VuAo4G5Jc9PWPGspb8gY4BrgUkafvJM3NAPHAA9KmpjhIW8CPh+CvEeJ/fBFRlniGGBpDp4jCbncBbgDODdNYq2leFB3AR4EjigoEw+3XjOB+zMMFbaZJpU3tAALMyTGA+yyaaM8aAcWA9ekpXnWUtgIJC0Afm4sVjZ0A6c757ZkaI5MzOnafCpDM+BO4Gf4lNwyoWaX6B2SxueaAMxe2Q+fXlvGkEYX8Dnn3LIMn2FajtdnYlbanqUlHwn8tIQkADAXuDfp5KGmBIW/BhwAXFsyNWwAm4Cj7abJEuOMiPKI/ix9E865HknH2nMcQv78JI1iupHAPs65VYmsWYLCfwS+GKWMdeMbgeOBW7Ou6rLwUGdO16kXWJV1KazVdCwBDishCYAvP/6sc25l5gRgav/hwNWMrnyyKNgALAJuj22yigNzmn3bzmYZSWAVsI9zbnXWBLAHcBMwtqTCf5Ld/FH4i0cCHcCVJSaBJ4D9nXPr6v0Hag0u8HS7+aPwR+QO1vDlS8D3KadjcBY+Oa0tOAGYLXo1vm1SFP6IPJPA6SUlgRqwN/D1etPUa3UKfxtwBbB7FP6ISAKZogn4It4Jnz4BmNPvRHzIr1ZC4V8UhT+SQMHQClxk2bejW5c6CGAmPt96XMkWcSDUF739JUbJowPLgUOdcyPOE6mNcvHa8A0hyyb8m4Bjo/BXQhPoAk4GflRCTWA+cMpoKghroxD+AdV/fskWrQufQhqFvzok0G2m3k9KRgJNZubMSNwEMPviXvKbhVYPuvEtoZfntW97RKrmQAs+df2wkr3aT4AjR9K2vTbChWoGziuh8B/onKuE8FuV5pCfCmsCPab9lc0cWAjslZgGIGkOfrhBWVJ9u/DOkuUlEOwavllJM36AymT8lJsO+/yZEX3zMPu3Bdg66M/vGzlutZ/deAfpJvvZjc/5//dP0U0nu+Cuo1wFRI/iU4W7GiIAU5N+jC/zLQM24TvqLCvSzW839cBsxEn40VV/wQczEifjMzLTPsBbjQgGZjCuw48UfxE/Cmsd0F20qUF2zq+hPAVE/XbOf7Sjcz4SApiPD/s1l2BRNmIlvXkXfsvsajehngn8jf2clmNTrB8/G2+lkcHj+KKVjUYK/Tlf81Z8FWFZQoRPAXvuSAtwIziEN5TESbKBD+L8eb3h2/BNNWYDe+K9uVMKTr5d+Mm5K4C7gF8C6/KqIVio+9v4zLqik0A/vmz4znoJYCrwtN1ERcZ6fNjnzjzdQma/j8M3etgTmGNCX/T13hHWmXZwL/AQsBo/tj1PJNCOryIsAwncCRw83FBSt5PDeSFwQQmE/yRyEue3m74TX8l1sN32kyhP49TRoNtMhIeA24BnMuy1OBQJXIFv0V1kEugB/rtz7oXREkC73f5To/AncqA68N1898cnU02uqNAPhy34ke034VNaV+Vkzy4vAQn8PfC/h9KydkQAc/CdfWtR+BtS8acBn8PHZqdQzpZpaezdU8CNwAONNLyIJABGrJ8YSrtyO1BTLwPOKugLDzj8MrH5LaS0B76+YB7lbJgSAr34EOOt+Iy9F7LwFZTAHOgHPu6cWzFSAmgBniXfLahzJ/w2SfgQfKhxRrztEz3AG4FlwFXAUxnsbdFJ4Gzn3DdHSgDTgecL+KIDcf5lIQ+IdUc6Dh9pmEg5+8/lBd3Aw/hQ3T3Oud6A+1zkEOEy4DPby8VwBHCMqVxFQvAMP7vxT8VXSXZGwQ+KrfjcgsUE9PMUOFloE/Cft/cD1Iax/z9RwFvhc6GE38ZzX4hPf70AH8uPwh8WzfhQ6k34ga1B2tOZAC2ieAVEHQwR0Rvq0NZsYYsk/PuHqOqT1CLpC8BvgP9FmNz7iB2jCT826zFJN0maZtGXNEmgx0zNopHArJESQFGcf134kt77Uhb8Jht4+hjeCRW9+vlDDTgI77y+UtKkNEudzfdQNBL465EQQCfF8F5vwpf03pOi4NckzQB+gC+ImhnlLPdoAU4BngS+2EjP/BGSwLHADwtCAhNHQgATC/AiG/EOv+UpCn8HcC4+GeoQYtZe0dCJD9vdJmlWWmaBFTWdRDG6DY+IACbk/CU28EGoL61bfzY+N/1ifJONiOKaBfPwzWwusKhNGiSwBR8Nuj7nJDB+JASQ59He603lSkv4xwJfA+7AO5aig68c6MDnw98haa96p+jshAS68Q0580wCLSMhgKYcC//xpJDkY7f+XOAWfAVkvPXLqQ0MhA0XSxqTAgl0GQl8D5/GnDe0FVUDSFP4W/CjlW7G1+PHW7/caMPXuNwkaUbSkQIjgTNNE+jN+2IMddj7KyT84/BZXZcSQ3tV9A3cBRyWtIOwSCQw1ItvrIjw724H4CjK0e8wYvSYgG8EelnS4cLtSCAvl2r3SAhgfZmF3+z9U/Bx/V2jDFQercBpwFJrgZcGCXwvJyRQGALYwAfe/iSFvwXf5+ByoqMv4sNyMBe425zBSZNAXqIDr42EANZm/JAb8dNakhb+MfiMvtOiyh8xDCYBt0g6PGES6CYfeQKrt/8PTcMI4BqyyQjswlf13ZNknF/SZBP+3Ut6cAc67b6CbwK5F7BLwt9xK74W4iP4fobTKWfvgzHA1ZImAN9Mqt+Ac26LpJNtvbLqJ/DKSAig3w5TaALYhG9ffF+Cgg8+tHeDsXvR0Y/3Kr+Gb4rxCPCEbWz/AGlKWoJv6JqkmfPIQEeZQaGzTvOjzOKDwSWdFD9tuhWfBfoRSefZDZ4ECfRIWmR/zYIEntwpATjn+iX9Ct/EMuTNf6Bz7oGEhX9v/My3Iof4ekwrexjrpe+cW72Tg7Za0rqECaBr0L8/8Mf1wD32GWiCugs+xPZpI4a2ghJCE76oaIKkk5JqTOqc2yrp+AxIYOBi36kGAPCLDG7+JIW/BuyLD/EUUfi32C3/M3y04pk6JumsNTU9CfQOJoAdHO5+fJeeFcA3ze8yBzgQ3wq9iNrBfkCrpKOdc2sTIoHeDEhgJd65PiICeMrsynEpP9RGs/nvS1j4D8In+HQU6KBtNaG/HV+L8ESD47M2JXx7dNdx0Dfa+9xudRYL+GAYSpGaqcwHrkuBBE6ytQ3RaPQeRpqUZLHy65Qu/mCFGSQp/JIOl/SOioO3Jd0h6QDrPJvUWixJ8Bk3W4VkIqaZpMmSviLpeUnvF2iv7pU0PkmplNQq6RpJfSk+d9+ow5uS5qf4UG9J2jsF4T9K0rsFOEh9kl6VdKmkmWnUqku6JMHnfVfStBSesUPSQZKWSvpjhUmgzUhgW0rP/Kw1Mx31Q/06hYf5vQl/LcEFRNLCgtz8v7Xbb3ya+p6k0xLWUtpTfNYmSbtL+kFBiOD+FEigXdLVKZHAOaO+bE2ovlgQ4d/DTIo84yVJZ6Qt+IPWZWGCh+nxNPvrbafFzSoIEdybdElxSiTwpuU01PVA4+zGyqXw2zPOtJfMK34v6QKrPAwGSVMSNIcWB372JiOCW3LuI7jR0svzTAKX1C1zxsjn5Fj4JydIUEnjXdvI1NtU72Dvfp7Ae7yfdH78KN6hxTSZp1N2kjXiy7k8hXOdFAm8JWlKow8zTtKLCTj8kl6kTkm/yumheFDSHEmZ1hxIWpDAIXowCwLbzsQbaxfR73O439sknZPCew+QQCPEt7jhvbMNOKHOB3nLQn21FG6GW3Ia0jsrTYdZHVpAI+HcxMJ/Cb3LdEm35VAb2KyEC4gGOeLrJYHXJU1Kko0eHOUDJB7nH0RIl+TsEPRJulvSLlneljvYu8fqfKcTQzj/6iD/E+1yyRPekTQvhfetJ0+gT9Ipie6dpHmjcCq9Y+pnGgfgKGPcPLH/GUk7gxJeswl1OEqX5I3MtrsEpki6K2cXwW8lTUyJ9K4dxbs+mLgWairY4qyY0J5hd1Oz8xTam523W3IYgVk8yncbT85h0YILJL2XozOxNI3LQFLzCEngD5J2S2vBx+xEnUxT+Cc26IxM2vFzo1JoLZ0iAVxSNgIY9H7zzebNizl4kdLJ7mzaCQlsM2001cXeZZjFTlP4W0zg8oD3zCNdK5CANJmPYjTYjwLBzJz7c2ISvGvhSwKSQJ85fFtCLPa++nDm3duS5qfo/f1CThJC3kprY1Per2ZJvxnlu55BwWAOs7TSaUeLV5VC/cSg/RzsGBwIPXeGXOzDTfDfSsvhZ9+Tl0y/5yXtVjThH6RBjdZ3cjEFhAnHV3LiKL5bfshsWns6QHYPqt503wbtyoUWHUjT53B/Djby/sRiqtmFAkerGi8pItkN0hqPyEGosE/SuWmZi6bxnKHAaeYh7dYLM7bp+uRr9ccXfC2n1PHuNxfJzzEMCcyX9LscmI275XWd8rzBc4AzMnzGfnxLrkVJdYHJEPVEKzqK/MLWnuw+/HyJNzJ8lE7gorxkhxaCAMxuuhBoz1D4fwIk1gwyY3RUjQCMBDASOJIhWmIHxHzgmDxqVLUcCn8NOM40gKyE/6fAqdbTrgwYU0UCGEQCDwFHM8RknEBoAr5Kck1aS60BTAPOy/DZlgNfKpHwQ32dkdspydAPI4FfAIvIbvTdOGBx3lLG81a40gxcZHZTFnjIbP71lAuV1QC2I4EH8CO6ujN6jL3xHasjAQyD/eyTBVYAR5fA4TcU/rxOtbW1ZCQw4Ng9Gz9wJQt5+3pauQGFJgD5rqWLyWZwxDoT/jWUE/XWLLSXbSGMBP4V+EdG2ic/WUwFclNmnScN4ERgSgbfuwU43jn3HOVFJIA/JYGL8M7eLHAe6Q/dKQ4BWFXdVzP46l7gPOfcMsqN9kgAf0ICvcBJ+ClYWRDy1yMBfIAvk43j73vAtyg/6hXktjIvinNuYBx9FolCJ0iaXnkCsA4qp2Tw1c8BZw+adFtm1Ot0ai/7wtik5ePxsxlDohm4OOvkoFrGwo+pQqEPWhdwrN0AVUBb4N8rGu4B/imD790b2K2yBIB3+h2Sgd1/PkPMSi8jjGSjCbBjLQDgYuCJDLSAM7OMCGRNACdncMjuBL5TEdV/QIjrDa22VmWRTBs8FT+yPiT2BWZUjgCsxPawwM+wDu/130p10Ih59R+oFlbgw4P9gQn61CpqAEcQNhbaj68wfKVih7qjwcNZGVh+wHfxdQMhcYAaHeFVJAKwVMhjA3//cuD7tslVQntGv1tkU+DrhK0XGIuPRFRGA1hI2Ky/jcD5zrluqodGhLiFauJR0wRCyuHhWXSeymJqbQs+Aytkzv938XH/KqIto98tshbQC1wW2FycgA8Lll4DmAvsGvD7VgNXVlD1jyZAY1gDXEE4h2AN+LykprITwKEBVct+4HLbTCIBRBNgFFoAwI8Ca467AruUlgCsffG8gF+5AvhhhWL+SRNAa5UXzjm3wS6QUGXDHcD+ZdYA9jBbJwR6gStK1tqrHvzHaAI0hFsJWzF4QMiGIcEIwIoeDiWc8+8FfNZf1dGII6+16otnYcHLCVcsNAWYXUYNYAqwe8Db/6p4+0cCSAj32IUSAs3A50JVCYYkgPmEy/xbhe/9FtGgD6DI04ES1gKuIVxEYDYwvjQEYLH/AwMtXj9wnTlwIhqP5UctwONn+JByCEwkUDQgFLtPIlx4Yz3ecRORDAG0xSUEmxD1o0BaQBPwdyHKhEMRwG7UN5yiHtxH9Qp+doRGPcpRA/gANwKbAn3XHALMZkidAMyG3DPQom0Bbqh43D/JG7wWNYAPYRXhmoZMtU/hNYCxhGt7tAp4OJ7TD6HRWH4kgA/MgH7TAkIkBrXiHeeFJ4DJhKn86wducs71xKP679pXawJ73BJX8kNYDoSaHvWptGcJhiCAPfCxzbTRTUz8Ger2bnSPow/gw1rABiDUHIldSTlzNlUCMPb6VKDFehlYGY9o4up7NAH+FLcQJjNwDClXzqatAXQSruHhHRUu+U1TeKMG8Kd4lHBjxj+ZZjgwbQKYSJjsv6340c8RyZoAtUgAQ5oBW/Dh5hCYmaYWljYBhPL+byCbGW95RxLVfNEEGBr3EiYpaBr1D3fNjgBMbflYoM14uGKtvkNpAAB/FpdxSDwEhIg4jSHFKFot5cM3NcAC9RsbR6Rjv0cTYGgzYC3hKgRnFZEA2gkT/+8lJv/saA9iHkB6COUH+FhaVZlpEsAkwuT/v0HM/U/Tfo9dgYbHzwP5ASalpYmlSQAzQ9liMfd/WCQx2iuaAMPjCcLkAxSLAMwB+FeBNuGxeA5Tvb0jAQzvB+gK5AcYm5Y2nZYG0EygjiaEn+NWNRMgEsDOtYC0UcOHAyMBbIeuaP/vEEnUk0cfwI7xZKDvKRwBdAZYlJWE69leVQ0gJgLtGCsCfc9/SyMSkBYBtAQigJejA3BoSGpPSAsbL+m4uKLDYnWgS6iTFFrqp0UA4wlTArwmnr8hhb8N38U2CbWxGbhC0mFxZYdEP74TVSEJIK0hHRMDLf4pdjC78b3attifu/Ajwf+AzxN4AnitCtqCpGbg28ABCRJ8G3CVpG7nXCV6Lpi6vQs+C++/4lNym027bbG1bceH6EKYSWMIO1G7ocU7Q/lBn6TNkm6RNK3khxZJF0valtJavilpRsnXsEnSIZKelPS+nZ884K00RoalZQL8pxzt6UBJ60LgSUlHlHHYheVeHAecleJNMR64TtLYkgr/eHyzjx/bzd9MNhO0h9PCCuMEzKvnuB24Drgo9Bz2AJgE/D3p5+7PBE4P0bM+sPBPxSeV7ZvTR2wlBb9aLYWFzHsTiRrwFeCYkt3+JwX0vZxI4Dn2AW7+24xE84y23BPAILYi5yRwmaTpJbr9jwj4fZ3A0WXQAuwdLielRJuE0VwEAihKG6l24MySEMAswqVeD2Bvwg17TdukWViQZ20pCgEUJXvsAEmFPsR2g32a8M6qKSUxAxYRJmcll5p1WgRQlCYS7fhRzEVGG+E6Lw9GE7B7wcmzBswr0CNHEyCFQ1z0uHZrhhrXxwseUp1IyoM38o40i4GKgo8WfA9bMiTcyaTYsTYAOshPnL80BBAqNzpJASoymjIk3KmEa/1e9YuqUBpAkUp0iz5NqJcwbamGE6CvppGiGgjrS7D/udQAijShd3XB93BLxhrXHOC0gvoC3iiYtho1gBSes+g9Bbvwk5GyPEPn4fMCCgXnXOVbyqdFAEWZ0rOh6AfAJiI9kfFjtAJLClpt+YMCmQE9RSCAIpkAlzrnNpaAyO/PgdY1HrhRUtGiAsvwo+UjAVQMDwH/UpJ3eQL4ZQ6eY1fgGkmFiaw453qALxXEbO0uAgH0ZmyTjgTPAAfb5hce1p9+SU4O8ULg4oI5Be8DvlEAEujNPQFY2611OV3AfuBRYH/n3AbKhZ8BD+TkWc4CvlCUakE7s183EujJ8dntKooJ8GYOF7AL+K4Jf+maiZoWcDb5aZR6KbBfgdav10jgaPy0n7xpA1tIwVmZSpdMSQvxrZWyVJV6bNE2AE8BVwNPOOdKnfgh6XAzB/JQkbkO+Kxz7qmCreFYYAFwIL7icSzJTFpudC0/6pzbVAQC2B14PMCiPGD2/B/xXYEHPj180Cl4LdBVlfkBZnufAFxMmOnMO8Mq4DPOuVcKupZj8QVDE40E2vlw7UUNOJ30eyO8DHzcOdddhIWbGKib6gVEDLX+SJon6fGcdLV9pOh9F3aw1k2S/hBoDQvREGTAXukKsP5/EcV9SHsW59wDwN/hux69kfEjzcbPFego4XJ3BtK0NlCEKMAgG3x9gEWZXrbutAkTwSbn3D8D/wPfNPQBsvFy1/DddhcXKUdgpGcwoA8gcQJIqzV2D94bPTXlRZmGr0jbGsV9h0SwBviOpO/jG4juhu+DMJYPSmJ3S/kwN+HnFrwu6RvmdS8DQrVFezUNP1aaBLAKmJ/yorTiO/o8E8V8RESwBT9ReeVQfhv8PME096wZOB9YJ+l7JXHMfjzQ96TiRK2ldNAAng+0MHOiaCemJRwK/IR0i2PagMvwYbYyYFaA7+gnpXqFNOOaLwTagE9G8U2MBDbiE2H+JWUSGANcLanQXYUlTSDMMJG1pORTS5MA1hAmEjCnhGO+siSBHnxc+3zSzYabiK8enFjg5ZpLmIm9r5BS45I0CaAbeC3A4oyh2H3p8kgC/c65fwCOJ92owXTghgKWEA9gz0Dfs6qoBBCi3VaTMXFE8rge2J90Q7pzgW9LaivSwpjWGWqmwNNpOUxTIwAL84TyA+wT8wFS2UOA5cBnSckLbTgMuFBSkbr07kqY0Wi9pBjlSru44THCtFuaScUHPKRJAs65J4wE0mw6cgZwSoH6CCwgTFvxNXgnYCEJYCVhmoO0AHtEcU2VCFbiq+OWp0TqNWAxcFAB1H+AfQJ93Up8UVshCWB9IDOgKeCGVJkE1gBHAj8knQhBC75mIO+5HZMIN1LuMWv8WjwCsJBSqI61c62OOyLdPd0AnAp8i3QiBGOA6yRNzfEy7EWYfgv9actPCHvrwUB+gLHRDAhGAl3AV4ELSSc8NdlIIHeEbur//oFkZw0pdywO8RIvp+nEGIRm4OAonsFIoAffQ+/UlGzUWcCVOaweDDkP8SlS7q8ZggDW4RMZQmAPSZOjeAYjgV58rsCRKZB8De8QPD9nkYGF+KnCIXBX2i3sagEOyVbgkUALNhYfU44IRwL9wJ2mFietrjbhw4OH5ET9bzeyC0FIGwjgPwvFrMtIYajBMO9zdIFTS4tKAljjz31IPlegDbhU0vQcvOrepN/jYgDPESCTNhQBrGKIGvSUMBnffSYiPBG8gm9Dtjzhf3qCkUBrhrd/E7CIMMk/APemGf4LSgDWyXRpoIVrAhaVsPVUUUhgA/AZ4DskG/1ZkLEpMJswtf+YtnxfiC8K6VxZTpjyYPCpwbFRSHYk0AucjB+0kdQt1gSclIUWYE7IRYSbtfAKgQaWhiSAFwgXDWgFji/YfLqykUA/8A8mOEkR/yT8FOLQmEbYDkYPWK5FeQjA+tEtDbiIC4h9AvJAAtfjW40l0Zq8iTANOLa//Y/Ht/8OgS7g5lDvF/qGDGkGjAG+HH0BmZMAzrmBkuJGy1o3kmJhzDDYBTgq4Pc9Q8Amt6EJYAVh59jvTUwPzgsRPIOvJlxG/c7Blwk4et76E5xNuBFr/cAPyjK2frhFPUrStoBjqR60BI6IfOz/GElLJL0/yn18z4bOhnzWeZLeDXhW/80ajZb6AIyV9NuAi7pN0jGxY1CuzkCLpK+NQrj6JN0QMgIgqU3SXYFnKF5ViXMq6eLAQyt/Lakzil6uzkCTpMMkvTkC4b8r9M0o6ZA6tJRG8K6kuVXZ/BmS3g64uH2Szo1hwdydAyTNkvTYMBfCW5IuDZ3abWbKrwLf/o9n0RPRZbTxNeAm4ICAX7se+LRzbkUUvdwRQQc+y25PfKPNbuBZ/DDT1WlXxA1xNi8EvkY4J3kvcKpz7jtV2vR9A6tYAw7BtihyETs4l3sEdvzJfGKZjE7PUiW+h/BDPecCp0VTIGI41R+4gnApv+BDf1c65zZVccEXBg4JStJmSTFDMOJPVH9JVyg8Xq1smNoW/ckMFv3XWZaWRuTyLO6VwWXUJ+mLVV/4fQOHBAdwWcwNiLAzOFbS6xmcwX+r/EWUoRawTdIB8fhXXvibJd2ibHBK3IFstYC3oz+g8pfPJRmdvXj7b7cRj2fEwi8VfEZ9RH1nDknHZRCKHrD9T4i78OENmZfRZkjS3bFgqJLn7e2MzttjsUx9aC3gmow2pM8KMZrjTlTirE2X9JuMztpmSbPjLgy9MZMk/S6jjXlf0jkxSaj0Z6xT0s+VHa60DsMRw2gBp2TklJGkP0o6MZJAac/XWEk3Z3i+Xi19vX8Cm9RuOfuKJBCRsPDflKHw98W+FCPfrLkZFGREEijveRqT8c0v62kQC9FGuGFNZitliVE+X9QAAAj/SURBVHcjCUThTwjvSNo97sboNm68pOdzQAInRBIo7BnqyIHw98m3P4tnaJSbh6T5po5nic3mmIye22Kdn05Jd2Qs/JK0NOaY1L+JNUkXKnv0Sbo85gkU5txMs4rPrPG6pKlxRxrbzHZJ9yofuEPS2Lgrudca38rBWdks6ZC8r5kryMbugh8rlocY6nPAwc65l4sqJPjZiWPx46468RN31uKHbmxxzhXxvZqAE4DLgazTbPuBbwFnhuxnWHZ2P0F+OEQe8KbdNLUCrV/NVONLJT07RPOLPnO6XiZpSsHerdXeqy8n5+OxqCkmv8nNkq7N0Sa/K+msIsR2zRt+iYWjRoI/mOe6JefvhaSp5mjLy7n4vaRZUWLT2fCxGWcJDuUcXCo/5yCvazZR0v11vt+SvNasy08XOkrZdPLZkd1/XJTUdDd+aoaVXMPhd2aitOZsrTrV+ICLJXmLfljR2LUZlo8PhW0WsYrx/gAHYE5OPL3bVxPeIGlKjm7ImxM62Kfk5J2a5DtJv5izve+TL2WPNf4BD8NhOXIKDsZLkg7PWhuQn223LUENpzPj95kk37b73Rzu+d3KaLBHlQmgZo6qvhweiPes+GOPLFRCc5g+kvANd0aGDswz5Kfn5HGvX5Q0PkpktpGBvOKP9nzTQjoJJe2Wwk35SAZ7e5CkpxW+X/9oPP4zoiRmSwJtyq6t80jxlvxI9LGB1uQLKdyWb4YIeVpob7ap1e/lnNwXFF1+Cu+xdM51A8cC9+X4MTuBrwBPSzotgL34lynsbQt+cm+awj8TuA64G1hA9hl9w6ELOBI/3zISQA5IYBPwOfw46Tyv9SR8qurz5r9IS6DSSJluBsak5MuZJ+k24BHgKMIO56xX+G8vYsp0KQnASGADcGgBWLlmAnoR8JKFj3ZL2EeQRvlpU5L/rhV5nQD8ym78/fA1CkThjwTQCAkcDNyKL8jI+9p3AMcBT5pWcK6kyQn0HqilRABtDQj8QM7+Akk3AL8DrgZ2tX8779hUNuGHglQD1nO7AFcBhxWQ5LYCjwI/AJYBG5xzvaN8/6eBpEee9QNHOud+OBqht1t9KvB54CAzg4qGjcDxwK1lEn4Kwrz1aAJdkk42YTqiYO/ZDMyzTxfwsKSlwHJgPSMr102D9GojUdFNe2kDpgOfxTvzdimwtrkBOKmMwl9aAhhEAqcae3/RBKtoaAf2tU8PsAL4haT7gZX2bt0Ba87bhhH4dnyEYDbwt8DuwOQSHKM1wJfKpvaX3gTY7oA2A2cB55Nv7/Jo0QWsss9L9nO12apLgTQSVL4JLMFHA6YAH7WbfpoJfFlapvUDLwCLnHNPlVk+Sk8ARgI1fLeYxaQQysoRek1lHZOSMHaZKl/m/vb9+HDySc651WWXjUoQgJEAwELgSvLRWiwinwT6feBs59zGKrywq9oOW7eWa1JSkSOKix7gH4FLnHNbqvLSroo7LWkiPky4dzz3EWbanAlcP9qQaySA4pJAG/D3wGmUx3kVMXq8BiwC7iurpz8SwPAk0AQcg89Ii6geVgIHAquqKPxQslTgUbOfV/fWRDmoLPqB16oq/JUnAAsPHhjloLKYbp9IABVFCz7LLqK65//gvLZ0jwSQPuYAsZ9btXEQJU6JjwQwvPoPvn9ARLUxBZgZCSCq/xHVxaGRAKqH+fhefRERC6s60afKBBDV/4gBTCL5BiqRAHJs/7cCe8VzHzFIDg6NBFAt9T+JsuB+fCLRWvLfg7Bs2AK8gu9/kAQOyNsQ1EgA6eHAhN59NbAn8Em7QX4CrIuymRp6geeA/wt82tb9y/bfG8UEfEejSqGK5cAd+A464xI4jMc7564f9G834cNKC40QZlDhGHOC2AQ8hB8a8qh1fx5Y82bgLnwPxUbxz8650yMBlJsADgJuTEAwHwU+5ZzbOsz3jLEb5WgzOeL02NGbVy8DP7P9enkHaz0buJ/GJwmtBv4q9gMoNwHchM/+avT239M599AIvq8Z72U+BD+zYAYxA3NH6B502z+Eb4u+szWu2f//iAa/eyvwGefcPZEAyin8ncDzNB7//ylw6Gi68VrmYTu+RfaB+CSkKVHeAd+N5xfAzfhZCGuHu+13sL6TbW8bnS70r865RZEAykkAR+HbgTWi/m8F/to5t6qB5xhorDnTyGA+fnhGlTSDbuAJfAfj203oexrc30uBcxp8rjVmBnRFAigfAdyGn0HXCP4fcHJSNeSmGbSYNrAXsA++r35LCbdgLX5241LgYfxcg94E13Is3sHbyBj2rcCBzrk7IwGUS/jHA882qP5vstvhjRSfc0A7mGVE8D/xWWrtpiEUQUvoNz/Ja3bLP2Iq/stJCvwwZHoWcFk0AyIBbH84jgCubVD9/zrwf0J3kLHw4gx884q/tD9Pw5cyN9knNDkMCHmv2fCv4FtsvWg/Vzjn1mawz+3A02ZS1YvVwMeqYAZUZTAIwI/xnvhGDsXfDI5B5+CdxgATjQjGAx+xv4+z/61jkObQtB1B1IYR6gH02t+3mqq+yX6+AbxuP9fazzcatd9TIPvrGiDEHuCzVYgGVCVJZYyp1I3cdpfgp+7kg7m9FrLRPit2oj20m1kx4FdoZuhOyFvsXfvxTrqugsbEbzXTo97MvhZ8hmdlwoFl1wDmSdqs+vGkqZYRxdnzvSW938CeP12F2oCqhJ12p/748FZgcVXCQiXCA/jwYr2YSDkmHEcCAD7RwO8ui6pg8WA+iUvMRKrXbJwaCaD4qmCTsXk92ETFZsWVDCuA6+v83UbOTSSAHKGpgfe8HvhllKPCagG9wBX4EGU9aI0EUHz0AOvr+L2VwGVVGxZZQrwGLMb7ckaDfvvdiBKYAcdJ2jYKD/B7kg6r8sCIku1/q6RbRhkF+K1lj0aU4AC0Sbp7hBvfJ+mqKraHKvkZmCbp1RGegfft0ogLV6IDMMHi+TvDvVZUElGu/R/IDXhnBML/NXMeR5TsELRLumiYQ9Anaan1DIgo5/7XJC2U9OYwwv+spAVVmhFQxY5A4NNi98IX1NTwDp8VwPLo9KvE/o/D920cIPstwH3Ac6Np8lIG/H+ZpGIVHaNm6gAAAABJRU5ErkJggg=="
help: |
  ## About
  The Timers plugin is an implementation of crond functionality. It allows events to be trigger on a scheduled time interval.

  ## Actions
  This plugin does not contain any actions.
  ## Triggers
  ### Hourly
  This trigger is used to create an hourly event with a user specified minute after the hour and an optional message.
  #### Input

  |Name|Type|Default|Required|Description|Enum|
  |----|----|-------|--------|-----------|----|
  |message|string|None|False|(optional) The message to send|None|
  |minute|integer|None|False|The minute after the hour to trigger the workflow|None|

  #### Output

  |Name|Type|Required|Description|
  |----|----|--------|-----------|
  |message|string|False|None|
  |time|string|False|None|

  ### Periodic
  This trigger is used to create a periodic event every *n* minutes with an optional message.

  #### Input

  |Name|Type|Default|Required|Description|Enum|
  |----|----|-------|--------|-----------|----|
  |message|string|None|False|A message to send with the event|None|
  |period|float|60|False|Minutes between events|None|

  #### Output

  |Name|Type|Required|Description|
  |----|----|--------|-----------|
  |message|string|False|None|
  |time|date|False|None|

  ### Daily
  This trigger is used to create a daily event with user supplied times and an optional message.
  #### Input

  |Name|Type|Default|Required|Description|Enum|
  |----|----|-------|--------|-----------|----|
  |message|string|None|False|(optional) The message to send|None|
  |times_in_utc|string|None|False|A comma-separated list of UTC times when you want the trigger to occur, e.g. 15\:04,01\:00,5\:00|None|

  #### Output

  |Name|Type|Required|Description|
  |----|----|--------|-----------|
  |message|string|False|None|
  |time|string|False|None|

  ### Weekly
  This trigger is used to create a weekly event with user supplied day of week and an optional message.
  #### Input

  |Name|Type|Default|Required|Description|Enum|
  |----|----|-------|--------|-----------|----|
  |message|string|None|False|(optional) The message to send|None|
  |times_in_utc|string|None|False|A comma-separated list of UTC times on those days when you want the trigger to occur|None|
  |days|string|None|False|Names of the days that you want the trigger|None|

  #### Output

  |Name|Type|Required|Description|
  |----|----|--------|-----------|
  |message|string|False|None|
  |time|string|False|None|

  ## Connection
  This plugin does not contain a connection.
  ## Troubleshooting
  This plugin does not contain any troubleshooting information.

  ## Workflows
  Examples:
  * Scheduling

  ## References
  * [Crontab](https://www.freebsd.org/cgi/man.cgi?crontab(5))

triggers:
  periodic:
    name: "Every X Minutes"
    description: "Trigger an event periodically"
    input:
      interval: 
        type: int
        description: "Seconds between events"
        default: 60
      message:
        type: string
        description: "A message to send with the event"
    output:
      message:
        type: string
      time:
        type: date
  
  hourly:
    name: "Hourly"
    description: "Trigger events hourly"
    input:
      minute:
        type: integer
        description: "The minute after the hour to trigger the workflow"
      message:
        type: string
        description: "(optional) The message to send"
    output:
      message:
        type: string
      time:
        type: date

  daily:
    name: "Daily"
    description: "Trigger events daily"
    input:
      times_in_utc:
        type: string
        description: "A comma-separated list of UTC times when you want the trigger to occur, e.g. 15:04,01:00,5:00"
      message:
        type: string
        description: "(optional) The message to send"
    output:
      message:
        type: string
      time:
        type: date

  weekly:
    name: "Weekly"
    description: "Trigger events weekly"
    input:
      days:
        type: string
        description: "Names of the days that you want the trigger"
      times_in_utc: 
        type: string
        description: "A comma-separated list of UTC times on those days when you want the trigger to occur"
      message:
        type: string
        description: "(optional) The message to send"
    output:
      message:
        type: string
      time:
        type: date
